### ISSUE TITLE
Uncaught ReferenceError: gl is not defined

### ISSUE THREAD

**Issue by sandrocantagallo** [valenzia10/PhonegapGoogleLogin#3]
Hello. 

I'm unable to use this module. 
I have installed dependecy plugin, and i have added GoogleLogin.js in www/js folder.

In my index.html i have loaded the js file:

 <script type="text/javascript" src="js/GoogleLogin.js"></script>
        <script type="text/javascript" src="js/index.js"></script>

in my index.js i write this:

onDeviceReady: function() {
        app.receivedEvent('deviceready');
        //document.addEventListener('deviceready', initApp, false);

```
    document.getElementById("google-login-button").addEventListener('click',startLogin,false);
    document.getElementById("google-logout-button").addEventListener('click',logout,false);

    var clientId = "757025673731-b324cmlq2tkvi5ajmcsm5np623jnr18p.apps.googleusercontent.com";
    var clientSecret = "KA_fsLKNeZrz3AEQ9gh2woty";

    // Create login object and initialize it with your app client id and secret
    var gl = new GoogleLogin(clientId, clientSecret);

    // Check if already logged in (i.e. access and refresh tokens in localStorage)
    gl.isLoggedIn(endLoginCheck);

     // facebookConnectPlugin.login(Array strings of permissions, Function success, Function failure)

     var fbLoginSuccess = function (userData) 
     {
         /*alert("UserInfo: " + JSON.stringify(userData));*/
        console.log("Facebook - Loggato con successo nel sistema");
     }

     function initApp()
     {
         console.log("Facebook - Avvio la procedura di Login");
         facebookConnectPlugin.login(["public_profile"],
             function (success) { alert("Ok" + success.authResponse.userID); console.log("Facebook Login Ok: " + JSON.stringify(success));restAuthFacebookLogin(success.authResponse.accessToken); },
             function (error) { alert("" + error) }
         );
     }


},
// Update DOM on a Received Event
receivedEvent: function(id) {
    var parentElement = document.getElementById(id);
    var listeningElement = parentElement.querySelector('.listening');
    var receivedElement = parentElement.querySelector('.received');

    listeningElement.setAttribute('style', 'display:none;');
    receivedElement.setAttribute('style', 'display:block;');

    console.log('Received Event: ' + id);
}
```

};

but in android console when i click on google+ button login i received this error:

07-08 11:13:18.276: E/Web Console(27432): Uncaught ReferenceError: gl is not defined:103

Waths wrong ?

**Comment by valenzia10** [comment]
Dear sandrocantagallo,

Sorry for the delay, I hope that by now you have already solved it. However, let me try to shed soe light into this. 

Your problem might be related to the fact that you are creating the gl object locally within the anonymous function used as onDeviceReady event handler. Thus, gl is scoped and other parts of your code cannot access it.

Since I really think it is not an issue from the module itself, but related to usage, I am closing this.

Best regards.
