### ISSUE TITLE
disallowed_useragent

### ISSUE THREAD

**Issue by san0suke** [valenzia10/PhonegapGoogleLogin#4]
Ao tentar logar, acontece um erro:
403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

**Comment by valenzia10** [comment]
Indeed, since the time this was published, Google's authorization processes and policies have changed. Thus, I am afraid that this module is no longer useful. I will update the Readme to state this as well.
